### ISSUE TITLE
Use default file name if FileLogSettings.FilePath ends with \ and no RollingStrategy options provided

### ISSUE THREAD

**Issue by terotgut** [vostok/logging.file#7]
Now if `FileLogSettings.FilePath` ends with \ with `RollingStrategy.Type = RollingStrategyType.None` there will be exception, if there is no such directory:

```
[FileLog] Failed to open log file 'c:\logs\archlogs\':
System.IO.DirectoryNotFoundException: Could not find a part of the path 'c:\logs\archlogs\'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Vostok.Logging.File.Helpers.FileSystem.OpenFile(FilePath file, FileOpenMode fileOpenMode, Encoding encoding, Int32 bufferSize) in D:\Cement\vostok.logging.file\Vostok.Logging.File\Helpers\FileSystem.cs:line 56
[FileLog] Failed to open log file 'c:\logs\archlogs\':
System.IO.DirectoryNotFoundException: Could not find a part of the path 'c:\logs\archlogs\'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Vostok.Logging.File.Helpers.FileSystem.OpenFile(FilePath file, FileOpenMode fileOpenMode, Encoding encoding, Int32 bufferSize) in D:\Cement\vostok.logging.file\Vostok.Logging.File\Helpers\FileSystem.cs:line 56
```

Instead of this, file logger can create directory and use default file name

**Comment by iloktionov** [comment]
Won't do in this form. But FileLog now just rejects settings with file path poiniting to a directory and the error message is much more clear:
https://github.com/vostok/logging.file/commit/1ef055ef382de41f60e7f5191bd02de5ccc4ffbc
